# site
title: itchyeggie
baseurl: "/itchyeggie"
url: "https://beckenkaru.github.io"
favicon: "/assets/images/ico.png"
g_analytics: UA-12345678-1

# bio
header: 
desc: >
  ÄGGIE

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
